// TestAction.java
package org.model;

public enum TestAction {
    OPEN, TYPE, CLICK, ACCEPT_ALERT, GET_TEXT, CLEAR_FIELD, CALL_METHOD, REFRESH, REFRESH_PAGE, QUIT, CHECK_VISIBLE, CHECK_ENABLED, GET_URL, NAV_FORWARD, NAV_BACK
}
