// TestAction.java
package org.model;

public enum TestAction {
    OPEN, TYPE, CLICK, ACCEPT_ALERT, GET_TEXT, CLEAR_FIELD, CALL_METHOD, REFRESH, REFRESH_PAGE, QUIT, CHECK_VISIBLE, CHECK_ENABLED, GET_URL, NAV_FORWARD, NAV_BACK, GET_TABLE_ROW, GET_TABLE_COLUMN, GET_TABLE_ELEMENT, SORT_TABLE_COLUMN, CHECK_COLUMN_SORTED, CHECK_COLUMN_SORTED_REV, CLICK_TABLE_ELEMENT
}
