name: Rest Assured Java API Automation CI

on:
  push:
    branches:
      - 'task2'
  pull_request:
    branches:
      - 'task2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
          mvn -version

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Verify environment
        run: |
          echo "Java version:"
          java -version
          echo "Maven version:"
          mvn -version

      - name: Execute test suite
        run: mvn test -Dsurefire.suiteXmlFiles=src/test/resources/test_suite_api.xml

      - name: Execute parallel test suite
        run: mvn test -Dsurefire.suiteXmlFiles=src/test/resources/test_suite_api_parallel.xml

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/

      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/
