name: Rest Assured Java API Automation CI

on:
  push:
    branches:
      - 'task2'
  pull_request:
    branches:
      - 'task2'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      api-service:
        image: simbirsoft_sdet_project-service:latest
        ports:
          - "8080:8080"
        options: --health-cmd "curl --fail http://localhost:8080 || exit 1" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Wait for API to be ready
        run: |
          echo "Waiting for API to be ready..."
          while ! curl --output /dev/null --silent --head --fail http://localhost:8080; do
            sleep 5
          done
          echo "API is ready!"

      - name: Run tests
        run: mvn test -Dsurefire.suiteXmlFiles=src/test/resources/test_suite_api.xml

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/