name: Run Selenium Tests (Java)

on:
  push:
    branches:
      - task1
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Установка Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Установка Chrome и WebDriver
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable
          CHROME_BIN=$(which google-chrome)
          echo "Chrome установлен по пути: $CHROME_BIN"
          sudo apt install -y chromium-chromedriver
          echo "WebDriver установлен"

      - name: Проверка установки Chrome
        run: google-chrome --version

      - name: Запуск тестов с TestNG
        run: mvn test -Dsurefire.suiteXmlFiles=test_suite.xml

      - name: Запуск параллельных тестов с TestNG
        run: mvn test -Dsurefire.suiteXmlFiles=test_suite_parallel.xml